// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type BackSourceInfo struct {

    /* ip回源配置，对应sourceType=ips的取值 (Optional) */
    Ips []IpSourceInfo `json:"ips"`

    /* 域名回源配置，对应sourceType=domain的取值 (Optional) */
    Domain []DomainSourceInfo `json:"domain"`

    /* oss回源配置，对应sourceType=oss的取值 (Optional) */
    OssSource string `json:"ossSource"`
}
